import { ParsedResume } from '../types/resume.types';
import { AnalysisScores, KeywordResult, Remark, ResumeAnalysisResponse } from '../types/analysis.types';
const skillDictionary = ['python','java','javascript','typescript','c','c++','html','css','react','next.js','angular','vue','node.js','express','django','flask','sql','mysql','postgresql','mongodb','aws','azure','docker','kubernetes','git','github','linux','figma','rest api','graphql','tailwind css','three.js'];
const actionVerbs = /\b(developed|built|created|designed|implemented|optimized|improved|automated|led|managed|integrated|launched|delivered|analyzed|engineered)\b/i;
const metricPattern = /\b\d+(?:\.\d+)?(?:%|\+|x|\s*(?:users|projects|teams|clients|months|years))?\b/i;
const clamp = (value: number) => Math.max(0, Math.min(100, Math.round(value)));
function words(text: string): string[] { return text.toLowerCase().replace(/[^a-z0-9+#.]+/g, ' ').split(/\s+/).map(word => word.replace(/^[.#]+|[.#]+$/g, '')).filter(word => word.length > 2); }
function keywordMatch(resume: string, jobDescription: string): KeywordResult { const resumeWords = new Set(words(resume)); const required = [...new Set(words(jobDescription).filter(word => skillDictionary.includes(word) || word.length > 4))]; const matched = required.filter(word => resumeWords.has(word)); return { matched, missing: required.filter(word => !resumeWords.has(word)), percentage: required.length ? clamp((matched.length / required.length) * 100) : 0 }; }
function contactScore(resume: ParsedResume): number { const fields = [resume.contact.email, resume.contact.phone, resume.contact.location, resume.contact.linkedin, resume.contact.github, resume.contact.website]; return clamp(fields.filter(Boolean).length / 6 * 100); }
function skillsScore(resume: ParsedResume, text: string): number { const found = skillDictionary.filter(skill => new RegExp(`(?<![a-z])${skill.replace(/[.+]/g, '\\$&')}(?![a-z])`, 'i').test(text)); return clamp(Math.min(found.length / 10, 1) * 75 + (resume.skills.length ? 25 : 0)); }
function experienceScore(resume: ParsedResume): number { if (!resume.experience.length) return 20; const bullets = resume.experience.filter(item => item.length > 25); const action = bullets.filter(item => actionVerbs.test(item)).length; const metrics = bullets.filter(item => metricPattern.test(item)).length; return clamp(30 + (bullets.length > 2 ? 20 : 0) + (action / Math.max(bullets.length, 1)) * 25 + (metrics / Math.max(bullets.length, 1)) * 25); }
function educationScore(resume: ParsedResume): number { if (!resume.education.length) return 50; const text = resume.education.join(' '); const degree = /b\.?\s?tech|b\.?e\.?|m\.?tech|mca|bca|mba|bachelor|master|diploma|degree/i.test(text); return clamp(60 + (degree ? 25 : 0) + (/[12][0-9]{3}/.test(text) ? 15 : 0)); }
function projectScore(resume: ParsedResume): number { if (!resume.projects.length) return 20; const text = resume.projects.join(' '); return clamp(35 + (resume.projects.length > 1 ? 15 : 0) + (/react|python|javascript|typescript|sql|api|docker/i.test(text) ? 20 : 0) + (metricPattern.test(text) ? 15 : 0) + (/github|https?:\/\//i.test(text) ? 15 : 0)); }
function atsScore(resume: ParsedResume, text: string): { score: number; issues: string[] } { const issues: string[] = []; let score = 100; const sections = [resume.summary, resume.skills.join(' '), resume.experience.join(' '), resume.education.join(' ')]; if (!resume.contact.email || !resume.contact.phone) { score -= 15; issues.push('Contact information is incomplete.'); } if (sections.filter(Boolean).length < 3) { score -= 20; issues.push('Several standard resume sections are missing.'); } if (text.length > 0 && text.split(/\n\s*\n/).some(block => block.length > 1000)) { score -= 10; issues.push('Some paragraphs are unusually long.'); } if ((text.match(/[★☆◆◇]/g) || []).length > 3) { score -= 10; issues.push('Decorative symbols may affect ATS parsing.'); } return { score: clamp(score), issues }; }
export function calculateOverallScore(scores: Omit<AnalysisScores, 'overall' | 'keywordMatch'> & { keywordMatch: number | null }, hasJobDescription: boolean): number { const weights: Record<string, number> = { ats: .2, content: .2, skills: .15, experience: .15, education: .1, formatting: .1, keywordMatch: .1 }; const available = hasJobDescription ? weights : Object.fromEntries(Object.entries(weights).filter(([key]) => key !== 'keywordMatch')); const weightTotal = Object.values(available).reduce((sum, weight) => sum + weight, 0); return clamp(Object.entries(available).reduce((sum, [key, weight]) => sum + (scores[key as keyof typeof scores] as number) * (weight / weightTotal), 0)); }
function remarks(resume: ParsedResume, scores: AnalysisScores, keywords: KeywordResult): { strengths: Remark[]; improvements: Remark[]; watchOuts: Remark[] } { const strengths: Remark[] = []; const improvements: Remark[] = []; const watchOuts: Remark[] = []; if (resume.skills.length >= 8) strengths.push({ message: 'The resume lists a useful range of relevant skills.', severity: 'low', category: 'skills' }); if (scores.experience >= 70) strengths.push({ message: 'Experience bullets show clear responsibilities and action-oriented language.', severity: 'low', category: 'experience' }); if (scores.ats >= 80) strengths.push({ message: 'The extracted structure is compatible with common ATS-style parsing.', severity: 'low', category: 'ats' }); if (!resume.summary) improvements.push({ message: 'Add a concise professional summary.', severity: 'medium', category: 'content' }); if (resume.experience.length && scores.experience < 65) improvements.push({ message: 'Add measurable outcomes to more experience bullets.', severity: 'medium', category: 'experience' }); if (resume.skills.length < 8) improvements.push({ message: 'Consider adding more relevant technical skills.', severity: 'medium', category: 'skills' }); if (!resume.projects.length) improvements.push({ message: 'Add relevant projects to demonstrate practical experience.', severity: 'low', category: 'projects' }); if (!resume.contact.linkedin) watchOuts.push({ message: 'Consider adding a LinkedIn profile.', severity: 'low', category: 'contact' }); if (!resume.contact.email || !resume.contact.phone) watchOuts.push({ message: 'Contact information is incomplete.', severity: 'high', category: 'contact' }); if (keywords.missing.length) improvements.push({ message: `Add relevant keywords such as: ${keywords.missing.slice(0, 5).join(', ')}.`, severity: 'medium', category: 'keywords' }); return { strengths, improvements, watchOuts }; }
export function analyzeParsedResume(resume: ParsedResume, text: string, jobDescription = ''): ResumeAnalysisResponse { const ats = atsScore(resume, text); const keyword = jobDescription.trim() ? keywordMatch(text, jobDescription) : { matched: [], missing: [], percentage: null }; const scoresWithoutOverall = { ats: ats.score, content: clamp((resume.summary ? 30 : 0) + (resume.experience.length ? 35 : 0) + (resume.achievements.length ? 20 : 0) + (text.length > 350 ? 15 : 5)), skills: skillsScore(resume, text), experience: experienceScore(resume), education: educationScore(resume), formatting: clamp(50 + (resume.summary ? 10 : 0) + (resume.experience.length ? 15 : 0) + (resume.education.length ? 15 : 0) + (text.split('\n').length > 8 ? 10 : 0)), keywordMatch: keyword.percentage }; const scores = { ...scoresWithoutOverall, overall: calculateOverallScore(scoresWithoutOverall, Boolean(jobDescription.trim())) }; const generated = remarks(resume, scores, keyword); return { success: true, scores, breakdown: { contactCompleteness: contactScore(resume), projectScore: projectScore(resume), skillCount: skillDictionary.filter(skill => new RegExp(skill.replace(/[.+]/g, '\\$&'), 'i').test(text)).length }, remarks: generated, keywords: keyword, parsedResume: resume }; }
